# vim ft=yaml
# travis-ci.org definition for Nimfa tests
language: python

sudo: false

cache: pip
apt: true

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
python:
#  - "2.7"
  - "3.4"
  - "3.5"

install:
  - travis_wait pip install numpy
  - travis_wait pip install --verbose scipy
  - pip install pep8 python-coveralls pytest-cov keras numpy pytest matplotlib mlp
  - pip install pandas
  - pip install scikit-learn
# Skip setup.py for now
#  - pip install -e .

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "export PYTHONPATH=$PYTHONPATH:."

script:
  - py.test --cov=polyssifier

after_success:
  - coveralls
